output:
  report_format: json
  update_frequency: weekly
search:
  glassdoor:
    enabled: true
    filters:
    - title
    - location
    url: https://glassdoor.com/jobs
  indeed:
    enabled: true
    filters:
    - title
    - company
    url: https://indeed.com/jobs
  linkedin:
    enabled: true
    filters:
    - title
    - location
    - experience
    url: https://linkedin.com/jobs/search
  locations:
  - London
  - EN37XQ
  - EC1Y8AF
  - SE19BG
  - Watford
  - WC2B5LX
  - Central London
  - Epsom
  - EC1M6PB
  - E149NN
  preferred_keywords:
  - go
  - azure
  - microservices
  - gcp
  - kubernetes
  - java
  required_keywords:
  - python
  - ruby
  - azure
  - microservices
  - java
  - spring
  - node.js
  - docker
  target_roles:
  - Senior Software Engineer
  - Staff Engineer
  - Tech Lead
  - Engineering Manager
platforms:
  linkedin:
    enabled: true
    max_results_per_search: 50
  glassdoor:
    enabled: true
    max_results_per_search: 50
  reed:
    enabled: true
    max_results_per_search: 50
  indeed:
    enabled: true
    max_results_per_search: 50
