output:
  report_format: json
  update_frequency: weekly
search:
  glassdoor:
    enabled: true
    filters:
    - title
    - location
    url: https://glassdoor.com/jobs
  indeed:
    enabled: true
    filters:
    - title
    - company
    url: https://indeed.com/jobs
  linkedin:
    enabled: true
    filters:
    - title
    - location
    - experience
    url: https://linkedin.com/jobs/search
  locations:
  - London
  - EN37XQ
  - SE10UH
  - EC1Y8AF
  - Watford
  - WC2B5LX
  - EC1M6PB
  - E149NN
  - SE10AA
  - WC2R0DT
  preferred_keywords:
  - azure
  - microservices
  - go
  - java
  - gcp
  - kubernetes
  - scala
  - angular
  - spring
  required_keywords:
  - microservices
  - azure
  - java
  - go
  target_roles:
  - Senior Software Engineer
  - Staff Engineer
  - Tech Lead
  - Engineering Manager
platforms:
  linkedin:
    enabled: true
    max_results_per_search: 50
  glassdoor:
    enabled: true
    max_results_per_search: 50
  reed:
    enabled: true
    max_results_per_search: 50
  indeed:
    enabled: true
    max_results_per_search: 50
